Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -35,6 +35,7 @@ jobs:
   docker:
     needs: build
     runs-on: ubuntu-latest
+  
 
     steps:
       - name: Checkout Repository
@@ -45,10 +46,17 @@ jobs:
         with:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}
+      - name: Verify Target Directory
+        run: ls -l target || echo "Target directory missing!"
 
       - name: Build Docker Image
         run: |
-          docker build -t ${{ secrets.DOCKER_USERNAME }}/hello-world:latest .
+          if [ -d "target" ]; then
+            docker build -t ${{ secrets.DOCKER_USERNAME }}/hello-world:latest .
+          else
+            echo "Error: Target directory does not exist. Build failed."
+            exit 1
+          fi
 
       - name: Push Docker Image
         run: |
